const debitAccounts = [
    "Yearly License Renewal Expenses",
    "Transit fees",
    "Repairs and Maintenance",
    "Bad debts",
    "Reconciliation Discrepancies",
    "Refund / Return",
    "Inventory Shrinkage",
    "Provision for Import Taxes",
    "Other Expenses",
    "Payroll Expenses",
    "FOUAD CBE",
    "Provision for Transit Fees",
    "Bakshish Bank Permit",
    "Office expenses",
    "Commissions and fees",
    "Import Transport Cost",
    "Provision for Transport Fees",
    "Amortisation expense",
    "Office Transport Cost",
    "Marine cargo insurance",
    "Travel expenses - general and admin expenses",
    "Legal and-or Consultancy fees",
    "Provision for ESL Fees",
    "Accounts Receivable (A/R)",
    "Staff Telephone Allowance",
    "COGS Cumulated",
    "Loading and Unloading",
    "ESL Custom Warehouse",
    "Inventory Asset",
    "Stationery and printing",
    "Meals and entertainment",
    "Bank charges",
    "Accrued liabilities",
    "Discounts given",
    "ESL Cost",
    "Dividend disbursed",
    "Import Transport Demurrage",
    "Exchange Gain or Loss",
    "Custom Taxes",
    "Available for sale assets (short-term)",
    "Purchases",
    "Sales Transport Cost",
    "Allowance for bad debt",
    "Shipping and delivery expense",
    "Import Transport Bakshish",
    "Warehouse Expense",
    "Insurance - General",
    "Staff Transport Allowance",
    "Rent or lease payments",
    "Provision for Rental Warehouse/Office",
    "Charity Fees - Bakshish",
    "Cost of sales",
    "Other Types of Expenses-Advertising Expenses",
    "Other general and administrative expenses",
    "Income tax expense"
  ];
  const creditAccounts = [
    "Opening Balance",
    "Sales of Product Income",
    "Retained Earnings",
    "Loan From-To Others",
    "Accounts Payable (A/P) - USD",
    "Share capital",
    "Opening Balance Equity",
    "Interest income",
    "Accounts Payable (A/P) - ETB",
    "Loan from Djib Customers",
    "Income tax payable"
  ];
  

  module.exports =  { debitAccounts, creditAccounts}